## これは何？

書籍 https://www.oreilly.co.jp/books/9784873115320/[言語実装パターン] のサンプルコードを Maven 化し、 現代的な IDE にインポートできるようにするためのスクリプトです。

オリジナルのコードは https://ant.apache.org/[Apache Ant] でプロジェクト構成されていますが、 2022 年現在もはやメジャーなツールではないためコードをビルドするハードルが上がってしまっています。

このコードサンプルを Maven プロジェクトとして取り扱えるようにすることで、上記の問題を解消します。

## 使い方

### セットアップ

次のコマンドを実行します:

[source]
----
./mavenize.sh
----

オリジナルのコードはオープンソース的ライセンスではないようなので、オライリーのサイトから各自で取得するようにしています。

### 実行方法

基本的には、各ディレクトリに移動し、次のコマンドを実行します:
[source]
----
mvn clean compile exec:java
----
追加の引数が必要な場合などは、次章で説明しています。

### IDE へ取り込む

TODO


## 書籍の説明箇所とコードの対応づけ

[cols="2", option="header"]
|===
|ページ
|ディレクトリ

|p.29
|parsing/lexer

|p.35
|parsing/recursive-descent

|p.39
|parsing/multi

|p.56
|parsing/memoize

|===

## 付録

### オリジナルの Ant を使うには

`build-macros.xml` の 62 行目で Java のバージョンを指定していますが、 `1.5` と古いので、ここを更新すれば動作するはずです。

### ANTLR3.2 は Java8 に対応していない

ソースコードには `antlr-3.2.jar` が同梱されていますが、どうやら Java7 までにしか対応していないようです。

Java17 で実行すると次のようなエラーが出ました。
[source]
----
internal error: Can't get property indirectDelegates using method get/isIndirectDelegates from org.antlr.tool.Grammar instance : java.lang.NullPointerException
----
検索してみると、このバージョンは Java7 までにしか対応していないようです。

* https://stackoverflow.com/a/22367682/4506703

https://www.antlr3.org/download.html[公式サイト]から最新版(これを書いた時点では `3.5.3` でした)をダウンロードしてそれを利用する必要があります。

ちなみにコマンドラインでの実行方法はこちらに説明があります。

* https://theantlrguy.atlassian.net/wiki/spaces/ANTLR3/pages/2687267/How+do+I+use+ANTLR+v3+from+the+command+line[How do I use ANTLR v3 from the command line? - ANTLR 3 - Confluence]

### サンプルコードが ANTLR3 で実行できない

理由がわからないので Stack Overflow で質問しています。

* https://stackoverflow.com/q/73476914/4506703
